### ISSUE TITLE
Improve the UI of the landing page

### ISSUE THREAD

**Issue by KhushiParekh** [this-mkhy/math-solver#2]
## 📝 Description
The main content currently occupies a small portion of the landing page, which impacts the overall user experience. To improve the UI, the main section should be expanded to make better use of the available space, providing a more engaging and visually balanced layout.

### 📷 Screenshot or Visual Reference (optional)
<img width="1438" alt="Screenshot 2024-10-22 at 10 30 57 PM" src="https://github.com/user-attachments/assets/12a4a196-7045-4775-9ba2-c0d9bfc44dea">

## 🐛 Bug Report (if applicable)

- **Expected behavior:** The main content should be clearly visible and take up more space to create a more visually appealing and immersive experience.
- **Actual behavior:** The main content occupies the left out space.

## 💡 Enhancement / Feature Request (if applicable)
Overall ui of the page

I would like to take on this task and fix the issue. Please assign it to me!

**Comment by KhushiSharma0313** [comment]
I would like to take on this task and fix the issue. Please assign it to me!

**Comment by log1-codes** [comment]
@this-mkhy i Can fix this easily please assign me the tasks to do it

**Comment by KhushiParekh** [comment]
@this-mkhy i had raised the issue first and i am already working on it. please assign the issue to me

**Comment by KhushiParekh** [comment]
this is the look:
<img width="1440" alt="Screenshot 2024-10-24 at 11 02 15 PM" src="https://github.com/user-attachments/assets/8473aca0-59bc-4a4e-aef9-7a5966fa7787">
<img width="1435" alt="Screenshot 2024-10-24 at 11 03 54 PM" src="https://github.com/user-attachments/assets/0ead308f-d992-4287-90d3-cfe6509d6ab0">

if it works ill open the pr , also please give the hactober tag

**Comment by KhushiParekh** [comment]
does this work?

**Comment by KhushiParekh** [comment]
@this-mkhy can you please add the hacktober tag so that i can raise the pr at the earliest

**Comment by this-mkhy** [comment]
@KhushiSharma0313 open the PR

**Comment by KhushiSharma0313** [comment]
Apologies for the delay, can I take some time to work and then open the PR, let me know thanks!
